project_id = "qylsxgewmasfpdofwedd"

[functions.send-contact-email]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.send-invite-accepted-email]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false
